### ISSUE TITLE
Testing routines for Policies 

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [PrincetonUniversity/SPECFEMPP#118]
### **Feature Description**
- **What does this feature do?**  
   Add testing routines for Range policies and Chunk Element policy

### **Implementation Plan**
- **Overview:**  
  How will this feature be implemented?
  Create Gtest routine to check if RangePolicy visits every quadrature point exactly once & Chunk element policy visits every quadrature point within a element exactly once
  
- **Subtasks:**
  - [x] #119
  - [x] #121
  - [x] #122

- **Dependencies:**  
  Any external tools, libraries, or APIs needed.
  GTest

### **Documentation**
Does the documentation need updating for this feature?

- [ ] Yes  
- [x] No

### **Checklist**
- [x] Code follows project guidelines.
- [x] Tests have been written and passed.
- [x] Documentation has been updated (if needed).
