### ISSUE TITLE
Add visualization capabilities - plotting fields

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [PrincetonUniversity/SPECFEMPP#126]
### **Feature Description**
- **What does this feature do?**  
   Implement visualization modules for plotting fields over the mesh. 

### **Implementation Plan**
- **Overview:**  
  How will this feature be implemented?
  The plan is to implement visualization using the [VTK](https://vtk.org/) library. 
  
- **Subtasks:**
  - [x] #127
  - [x] #130
  - [x] #132
  - [x] #136
  - [x] #140
  - [ ] #143
  - [x] #142

- **Dependencies:**  
  VTK

### **Documentation**
Does the documentation need updating for this feature?

- [x] #168
- [x] #175

### **Checklist**
- [ ] Code follows project guidelines.
- [ ] Tests have been written and passed.
- [ ] Documentation has been updated (if needed).
