### ISSUE TITLE
Adding tests for SPECFEM++ assembly

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [PrincetonUniversity/SPECFEMPP#134]
### **Feature Description**
- **What does this feature do?**  
  Update testing infrastructure for SPECFEM++ spectral element assembly
  
- **Problem Addressed:**  
  Better testing infrastructure. The newer testing infrastructure will implement focussed unit-testing. This should enable us to find bugs much faster

### **Implementation Plan**
- **Overview:**  
  How will this feature be implemented?
  
- **Subtasks:** (Need to be updated)
  - [ ] Task 1
  - [ ] Task 2
  - [ ] Task 3

- **Dependencies:**  
  Gtest

### **Documentation**
Does the documentation need updating for this feature?

- [ ] Yes  
- [x] No

### **Checklist**
- [x] Code follows project guidelines.
- [x] Tests have been written and passed.
- [x] Documentation has been updated (if needed).
