### ISSUE TITLE
Fluid-solid bathymetry example

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [PrincetonUniversity/SPECFEMPP#158]
### **Feature Description**
- **What does this feature do?**  
  Integrate Fluid-solid bathymetry example contributed by Ivy from their [publication](https://doi.org/10.1093/gji/ggae238) 
  
### **Motivation**
The example demonstrates to implement  a plane wave (teleseismic wave) at the domain boundaries

### **Implementation Plan**
  
- **Subtasks:**
  - [ ] Merge Ivy's PR to this issue
  - [ ] Task 2
  - [ ] Task 3

- **Dependencies:**  
  Any external tools, libraries, or APIs needed.

### **Testing Plan**
How will the feature be tested? List any test cases:

- [ ] Test case 1
- [ ] Test case 2

### **Documentation**
Does the documentation need updating for this feature?

- [ ] Yes  
- [ ] No

### **Checklist**
- [ ] Code follows project guidelines.
- [ ] Tests have been written and passed.
- [ ] Documentation has been updated (if needed).
