### ISSUE TITLE
Move IO backends to `IO_backends` namespace

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [PrincetonUniversity/SPECFEMPP#167]
### **Feature Description**
- **What does this feature do?**  
  Move `fortran`, `HDF5` and `ASCII` implementations from IO namespace `IO_backends` namespace 
  
- **Problem Addressed:**  
  IO library should provide access to routines required for reading meshes only. This is the namespace which will be exposed to end developers

### **Implementation Plan**
  
- **Subtasks:**
  - [ ] Task 1
  - [ ] Task 2
  - [ ] Task 3

### **Documentation**
Does the documentation need updating for this feature?

- [ ] Yes  
- [ ] No

### **Checklist**
- [ ] Code follows project guidelines.
- [ ] Tests have been written and passed.
- [ ] Documentation has been updated (if needed).

---
**Type**: Feature  
**Priority**: [Low/Medium/High]  
**Status**: [Pending Review/In Progress/Complete]  
**Assignee**:  
**Reviewer**:

**Comment by lsawade** [comment]
Do you not want it to be in `IO/backends`?
